In [61]:
import json

In [62]:
years=['2020','2021','2022','2023','2024']
datas=['1.json','2.json','3.json','4.json']

In [63]:
collected_data=[]
for year in years:
    for data in datas:
        try:
            with open(f'/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/{year}/{data}','r') as file :
                data=json.load(file)
                collected_data.append(data)
        except Exception as error:
            print(f'error due to {error}')

error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/2020/1.json'

In [64]:
import pandas as pd 
pd.json_normalize(collected_data)
# collected_data

,success,code,responseTimestamp,data.from,data.to,data.transactionData
0,True,SUCCESS,1692610792790,1585679400000,1593282600000,"[{'name': 'Insurance', 'paymentInstruments': [..."
1,True,SUCCESS,1692610844644,1593541800000,1601231400000,"[{'name': 'Insurance', 'paymentInstruments': [..."
2,True,SUCCESS,1692610897678,1601490600000,1609093800000,"[{'name': 'Insurance', 'paymentInstruments': [..."
3,True,SUCCESS,1692610949539,1609439400000,1616869800000,"[{'name': 'Insurance', 'paymentInstruments': [..."
4,True,SUCCESS,1692611001440,1617215400000,1624818600000,"[{'name': 'Insurance', 'paymentInstruments': [..."
5,True,SUCCESS,1692611053830,1625077800000,1632767400000,"[{'name': 'Insurance', 'paymentInstruments': [..."
6,True,SUCCESS,1692611105286,1633026600000,1640629800000,"[{'name': 'Insurance', 'paymentInstruments': [..."
7,True,SUCCESS,1692611156795,1640975400000,1648405800000,"[{'name': 'Insurance', 'paymentInstruments': [..."
8,True,SUCCESS,1692611208275,1648751400000,1656354600000,"[{'name': 'Insurance', 'paymentInstruments': [..."
9,True,SUCCESS,1692611259689,1656613800000,1664303400000,"[{'name': 'Insurance', 'paymentInstruments': [..."
10,True,SUCCESS,1692611311480,1664562600000,1672165800000,"[{'name': 'Insurance', 'paymentInstruments': [..."
11,True,SUCCESS,1692619156204,1672511400000,1679941800000,"[{'name': 'Insurance', 'paymentInstruments': [..."
12,True,SUCCESS,1692619338381,1680287400000,1687890600000,"[{'name': 'Insurance', 'paymentInstruments': [..."
13,True,SUCCESS,1697612170056,1688149800000,1695839400000,"[{'name': 'Insurance', 'paymentInstruments': [..."
14,True,SUCCESS,1706092828151,1696098600000,1703701800000,"[{'name': 'Insurance', 'paymentInstruments': [..."
15,True,SUCCESS,1714727714707,1704047400000,1711564200000,"[{'name': 'Insurance', 'paymentInstruments': [..."
16,True,SUCCESS,1722517837749,1711909800000,1719513000000,"[{'name': 'Insurance', 'paymentInstruments': [..."
17,True,SUCCESS,1739974365115,1719792000000,1727481600000,"[{'name': 'Insurance', 'paymentInstruments': [..."
18,True,SUCCESS,1739974587175,1727740800000,1735344000000,"[{'name': 'Insurance', 'paymentInstruments': [..."

In [65]:
collected_data2=[]
countries=['andhra-pradesh','assam','bihar','chandigarh','chhattisgarh','dadra-&-nagar-haveli-&-daman-&-diu','delhi','goa','gujarat','haryana','himachal-pradesh','jammu-&-kashmir','jharkhand','karnataka','kerala','ladakh','lakshadweep','madhya-pradesh','maharashtra','manipur','meghalaya','mizoram','nagaland','odisha','puducherry','punjab','rajasthan','sikkim','tamil-nadu','telangana','tripura','uttar-pradesh','uttarakhand','west-bengal']
for country in countries:
    for year in years:
        for data in datas:
            try:
                with open(f'/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/{country}/{year}/{data}') as file:
                    data=json.load(file)
                    collected_data2.append(data)
            except Exception as error:
                print(f'error due to {error}')

error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/andhra-pradesh/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/assam/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/bihar/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/chandigarh/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/chhattisgarh/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/dadra-&-nagar-haveli-&-daman-&-diu/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/delhi/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/goa/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/gujarat/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/haryana/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/himachal-pradesh/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/jammu-&-kashmir/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/jharkhand/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/karnataka/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/kerala/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/ladakh/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/lakshadweep/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/madhya-pradesh/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/maharashtra/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/manipur/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/meghalaya/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/mizoram/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/nagaland/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/odisha/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/puducherry/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/punjab/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/rajasthan/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/sikkim/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/tamil-nadu/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/telangana/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/tripura/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/uttar-pradesh/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/uttarakhand/2020/1.json'
error due to [Errno 2] No such file or directory: '/Users/bootlabs/guvi project-1/pulse/data/aggregated/insurance/country/india/state/west-bengal/2020/1.json'

In [66]:
pd.json_normalize(collected_data2)

,success,code,responseTimestamp,data.from,data.to,data.transactionData
0,True,SUCCESS,1692610800646,1585679400000,1593282600000,"[{'name': 'Insurance', 'paymentInstruments': [..."
1,True,SUCCESS,1692610852100,1593541800000,1601231400000,"[{'name': 'Insurance', 'paymentInstruments': [..."
2,True,SUCCESS,1692610905229,1601490600000,1609093800000,"[{'name': 'Insurance', 'paymentInstruments': [..."
3,True,SUCCESS,1692610956969,1609439400000,1616869800000,"[{'name': 'Insurance', 'paymentInstruments': [..."
4,True,SUCCESS,1692611008959,1617215400000,1624818600000,"[{'name': 'Insurance', 'paymentInstruments': [..."
...,...,...,...,...,...,...
641,True,SUCCESS,1706092874310,1696098600000,1703701800000,"[{'name': 'Insurance', 'paymentInstruments': [..."
642,True,SUCCESS,1714727757342,1704047400000,1711564200000,"[{'name': 'Insurance', 'paymentInstruments': [..."
643,True,SUCCESS,1722517887689,1711909800000,1719513000000,"[{'name': 'Insurance', 'paymentInstruments': [..."
644,True,SUCCESS,1739974413543,1719792000000,1727481600000,"[{'name': 'Insurance', 'paymentInstruments': [..."
645,True,SUCCESS,1739974635383,1727740800000,1735344000000,"[{'name': 'Insurance', 'paymentInstruments': [..."

In [67]:
len(collected_data2)

646

In [68]:
years=['2018','2019','2020','2021','2022','2023','2024']
datas=['1.json','2.json','3.json','4.json']

In [69]:
collected_data3=[]
for year in years:
    for data in datas:
        try:
            with open(f'/Users/bootlabs/guvi project-1/pulse/data/aggregated/transaction/country/india/{year}/{data}') as file:
                data=json.load(file)
                collected_data3.append(data)
        except Exception as error :
            print(f'error due to {error}')

In [70]:
collected_data3

[{'success': True,
  'code': 'SUCCESS',
  'data': {'from': 1514745000000,
   'to': 1522175400000,
   'transactionData': [{'name': 'Recharge & bill payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 72550406,
       'amount': 14472713558.652578}]},
    {'name': 'Peer-to-peer payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 46982705,
       'amount': 147245883542.77402}]},
    {'name': 'Merchant payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 5368669,
       'amount': 4656678915.140091}]},
    {'name': 'Financial Services',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 3762820,
       'amount': 815853105.1000277}]},
    {'name': 'Others',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 5761576,
       'amount': 4643217301.269438}]}]},
  'responseTimestamp': 1630346628866},
 {'success': True,
  'code': 'SUCCESS',
  'data': {'from': 1522521000000,
   'to': 1530124200000,
   'transactionData': [{'name': 'Recharge & bill payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 92033715,
       'amount': 24351225616.36898}]},
    {'name': 'Peer-to-peer payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 74558816,
       'amount': 264767671095.31842}]},
    {'name': 'Merchant payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 10613941,
       'amount': 9052859939.339659}]},
    {'name': 'Financial Services',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 5186569,
       'amount': 1176991419.239996}]},
    {'name': 'Others',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 4973199,
       'amount': 5027454207.140578}]}]},
  'responseTimestamp': 1630501481910},
 {'success': True,
  'code': 'SUCCESS',
  'data': {'from': 1530383400000,
   'to': 1538073000000,
   'transactionData': [{'name': 'Peer-to-peer payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 202021587,
       'amount': 425967421714.0399}]},
    {'name': 'Recharge & bill payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 102290514,
       'amount': 31364311860.394596}]},
    {'name': 'Merchant payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 25175938,
       'amount': 12433150984.830223}]},
    {'name': 'Financial Services',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 6218596,
       'amount': 891447809.4200314}]},
    {'name': 'Others',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 5594554,
       'amount': 4449556277.54975}]}]},
  'responseTimestamp': 1630501481911},
 {'success': True,
  'code': 'SUCCESS',
  'data': {'from': 1538332200000,
   'to': 1545935400000,
   'transactionData': [{'name': 'Peer-to-peer payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 200235002,
       'amount': 594995709377.7327}]},
    {'name': 'Recharge & bill payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 131917248,
       'amount': 39578607327.024284}]},
    {'name': 'Merchant payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 71498510,
       'amount': 30497289208.339787}]},
    {'name': 'Financial Services',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 5216165,
       'amount': 868584631.5900131}]},
    {'name': 'Others',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 8246415,
       'amount': 5802659774.449921}]}]},
  'responseTimestamp': 1630501481911},
 {'success': True,
  'code': 'SUCCESS',
  'data': {'from': 1546281000000,
   'to': 1553711400000,
   'transactionData': [{'name': 'Peer-to-peer payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 404841331,
       'amount': 887893108631.5128}]},
    {'name': 'Recharge & bill payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 180504739,
       'amount': 55473071028.87885}]},
    {'name': 'Merchant payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 110496541,
       'amount': 40575915112.522}]},
    {'name': 'Financial Services',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 4627353,
       'amount': 603852042.0000324}]},
    {'name': 'Others',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 8526177,
       'amount': 5484252454.8204155}]}]},
  'responseTimestamp': 1630501482108},
 {'success': True,
  'code': 'SUCCESS',
  'data': {'from': 1554057000000,
   'to': 1561660200000,
   'transactionData': [{'name': 'Peer-to-peer payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 384711008,
       'amount': 1196425281586.9927}]},
    {'name': 'Recharge & bill payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 209898072,
       'amount': 76865848586.98372}]},
    {'name': 'Merchant payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 206467182,
       'amount': 73415840739.88434}]},
    {'name': 'Financial Services',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 2650384,
       'amount': 545329308.0899862}]},
    {'name': 'Others',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 11656557,
       'amount': 6969423863.830339}]}]},
  'responseTimestamp': 1630501482108},
 {'success': True,
  'code': 'SUCCESS',
  'data': {'from': 1561919400000,
   'to': 1569609000000,
   'transactionData': [{'name': 'Peer-to-peer payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 461911865,
       'amount': 1440512511470.7004}]},
    {'name': 'Merchant payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 376320628,
       'amount': 123209398484.44376}]},
    {'name': 'Recharge & bill payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 240103872,
       'amount': 101520929811.06812}]},
    {'name': 'Financial Services',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 2870292,
       'amount': 617120839.9299941}]},
    {'name': 'Others',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 13804992,
       'amount': 6705143103.510092}]}]},
  'responseTimestamp': 1630501482108},
 {'success': True,
  'code': 'SUCCESS',
  'data': {'from': 1569868200000,
   'to': 1577471400000,
   'transactionData': [{'name': 'Peer-to-peer payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 703497002,
       'amount': 1963952535223.0903}]},
    {'name': 'Merchant payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 456578271,
       'amount': 174239646473.03162}]},
    {'name': 'Recharge & bill payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 285310032,
       'amount': 116344996244.26738}]},
    {'name': 'Financial Services',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 2476840,
       'amount': 551204225.4200497}]},
    {'name': 'Others',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 12583379,
       'amount': 4811822509.649999}]}]},
  'responseTimestamp': 1630501482108},
 {'success': True,
  'code': 'SUCCESS',
  'data': {'from': 1577817000000,
   'to': 1585333800000,
   'transactionData': [{'name': 'Peer-to-peer payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 693998661,
       'amount': 2320557268853.593}]},
    {'name': 'Merchant payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 566355270,
       'amount': 231298042209.83606}]},
    {'name': 'Recharge & bill payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 351300991,
       'amount': 140373550367.1558}]},
    {'name': 'Financial Services',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 1358171,
       'amount': 773848137.0300016}]},
    {'name': 'Others',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 10027019,
       'amount': 4116905195.8207293}]}]},
  'responseTimestamp': 1630501482109},
 {'success': True,
  'code': 'SUCCESS',
  'data': {'from': 1585679400000,
   'to': 1593282600000,
   'transactionData': [{'name': 'Peer-to-peer payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 631031364,
       'amount': 2243915932390.771}]},
    {'name': 'Recharge & bill payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 448842692,
       'amount': 171590686463.15784}]},
    {'name': 'Merchant payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 363275861,
       'amount': 226908226049.51398}]},
    {'name': 'Financial Services',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 1682062,
       'amount': 1751767444.1000087}]},
    {'name': 'Others',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 3779461,
       'amount': 1987466180.2098684}]}]},
  'responseTimestamp': 1630501482109},
 {'success': True,
  'code': 'SUCCESS',
  'data': {'from': 1593541800000,
   'to': 1601231400000,
   'transactionData': [{'name': 'Peer-to-peer payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 916790263,
       'amount': 3287051873253.504}]},
    {'name': 'Merchant payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 672019839,
       'amount': 405291207894.2984}]},
    {'name': 'Recharge & bill payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 436172619,
       'amount': 204262355709.72183}]},
    {'name': 'Financial Services',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 2531978,
       'amount': 2673063432.9600067}]},
    {'name': 'Others',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 5541374,
       'amount': 2789907563.6502213}]}]},
  'responseTimestamp': 1630501482114},
 {'success': True,
  'code': 'SUCCESS',
  'data': {'from': 1601490600000,
   'to': 1609093800000,
   'transactionData': [{'name': 'Peer-to-peer payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 1249512647,
       'amount': 4474548495095.518}]},
    {'name': 'Merchant payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 1127490136,
       'amount': 684873639322.252}]},
    {'name': 'Recharge & bill payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 479784084,
       'amount': 227875840842.1121}]},
    {'name': 'Financial Services',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 2942567,
       'amount': 3259168195.749941}]},
    {'name': 'Others',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 9556404,
       'amount': 5323095366.309718}]}]},
  'responseTimestamp': 1630501482413},
 {'success': True,
  'code': 'SUCCESS',
  'data': {'from': 1609439400000,
   'to': 1616869800000,
   'transactionData': [{'name': 'Merchant payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 1467948823,
       'amount': 844466633896.8679}]},
    {'name': 'Peer-to-peer payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 1447600942,
       'amount': 5170856441552.582}]},
    {'name': 'Recharge & bill payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 530118545,
       'amount': 260182440730.4327}]},
    {'name': 'Financial Services',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 3075296,
       'amount': 3573884778.5300817}]},
    {'name': 'Others',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 8851525,
       'amount': 5199901891.8900385}]}]},
  'responseTimestamp': 1630501482413},
 {'success': True,
  'code': 'SUCCESS',
  'data': {'from': 1617215400000,
   'to': 1624818600000,
   'transactionData': [{'name': 'Peer-to-peer payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 1744272888,
       'amount': 6163165772736.494}]},
    {'name': 'Merchant payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 1499626469,
       'amount': 1003530942287.5988}]},
    {'name': 'Recharge & bill payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 685024821,
       'amount': 300559461295.9022}]},
    {'name': 'Financial Services',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 3397384,
       'amount': 3651996523.4499955}]},
    {'name': 'Others',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 9061732,
       'amount': 5598131364.820071}]}]},
  'responseTimestamp': 1630501482414},
 {'success': True,
  'code': 'SUCCESS',
  'data': {'from': 1625077800000,
   'to': 1632767400000,
   'transactionData': [{'name': 'Merchant payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 2316924871,
       'amount': 1426965558783.5557}]},
    {'name': 'Peer-to-peer payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 2215575286,
       'amount': 7429357587018.912}]},
    {'name': 'Recharge & bill payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 714583744,
       'amount': 349234592690.4992}]},
    {'name': 'Financial Services',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 3112160,
       'amount': 4043342762.3300233}]},
    {'name': 'Others',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 13558464,
       'amount': 7146868847.2897215}]}]},
  'responseTimestamp': 1634575058405},
 {'success': True,
  'code': 'SUCCESS',
  'data': {'from': 1633026600000,
   'to': 1640629800000,
   'transactionData': [{'name': 'Merchant payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 3152394530,
       'amount': 1995855822160.6426}]},
    {'name': 'Peer-to-peer payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 2716561423,
       'amount': 9203910371491.78}]},
    {'name': 'Recharge & bill payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 738096162,
       'amount': 407266894783.10693}]},
    {'name': 'Financial Services',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 4141629,
       'amount': 5028434834.240034}]},
    {'name': 'Others',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 14562602,
       'amount': 9296993478.869577}]}]},
  'responseTimestamp': 1643295672713},
 {'success': True,
  'code': 'SUCCESS',
  'data': {'from': 1640975400000,
   'to': 1648405800000,
   'transactionData': [{'name': 'Merchant payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 3748851071,
       'amount': 2272818129376.5205}]},
    {'name': 'Peer-to-peer payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 3074250150,
       'amount': 10505936803336.926}]},
    {'name': 'Recharge & bill payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 749674246,
       'amount': 447599848131.41187}]},
    {'name': 'Financial Services',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 4035100,
       'amount': 4921211866.489969}]},
    {'name': 'Others',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 16393502,
       'amount': 8422766458.459174}]}]},
  'responseTimestamp': 1651127570915},
 {'success': True,
  'code': 'SUCCESS',
  'data': {'from': 1648751400000,
   'to': 1656354600000,
   'transactionData': [{'name': 'Merchant payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 4765203787,
       'amount': 2847096877386.341}]},
    {'name': 'Peer-to-peer payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 3506141323,
       'amount': 12123524700463.535}]},
    {'name': 'Recharge & bill payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 845751926,
       'amount': 523046092987.93964}]},
    {'name': 'Financial Services',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 3272822,
       'amount': 3889787479.819907}]},
    {'name': 'Others',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 11241480,
       'amount': 6711034131.16017}]}]},
  'responseTimestamp': 1669732200356},
 {'success': True,
  'code': 'SUCCESS',
  'data': {'from': 1656613800000,
   'to': 1664303400000,
   'transactionData': [{'name': 'Merchant payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 5618132071,
       'amount': 3151614767860.314}]},
    {'name': 'Peer-to-peer payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 3957113406,
       'amount': 12837803371386.29}]},
    {'name': 'Recharge & bill payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 956164949,
       'amount': 607048699730.3645}]},
    {'name': 'Financial Services',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 3959631,
       'amount': 4514223164.469998}]},
    {'name': 'Others',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 10005043,
       'amount': 6725900102.770244}]}]},
  'responseTimestamp': 1669732331633},
 {'success': True,
  'code': 'SUCCESS',
  'data': {'from': 1664562600000,
   'to': 1672165800000,
   'transactionData': [{'name': 'Merchant payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 6565690145,
       'amount': 3673601044800.037}]},
    {'name': 'Peer-to-peer payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 4459859921,
       'amount': 14578874324207.227}]},
    {'name': 'Recharge & bill payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 991049281,
       'amount': 649776847580.25}]},
    {'name': 'Financial Services',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 4623387,
       'amount': 5360528394.309982}]},
    {'name': 'Others',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 10013085,
       'amount': 7361492606.590162}]}]},
  'responseTimestamp': 1674558208918},
 {'success': True,
  'code': 'SUCCESS',
  'data': {'from': 1672511400000,
   'to': 1679941800000,
   'transactionData': [{'name': 'Merchant payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 7205999708,
       'amount': 3745994748195.0}]},
    {'name': 'Peer-to-peer payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 4792478560,
       'amount': 15924876501456.0}]},
    {'name': 'Recharge & bill payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 1076952638,
       'amount': 829952832616.0}]},
    {'name': 'Financial Services',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 4884759,
       'amount': 5673343900.0}]},
    {'name': 'Others',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 10259195,
       'amount': 7571900579.0}]}]},
  'responseTimestamp': 1692619032318},
 {'success': True,
  'code': 'SUCCESS',
  'data': {'from': 1680287400000,
   'to': 1687890600000,
   'transactionData': [{'name': 'Merchant payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 8529595637,
       'amount': 4277821161887.0}]},
    {'name': 'Peer-to-peer payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 5374546962,
       'amount': 17722778868673.0}]},
    {'name': 'Recharge & bill payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 1190947064,
       'amount': 904758857308.0}]},
    {'name': 'Financial Services',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 5195942,
       'amount': 6364033676.0}]},
    {'name': 'Others',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 9341245,
       'amount': 6919677602.0}]}]},
  'responseTimestamp': 1692619213030},
 {'success': True,
  'code': 'SUCCESS',
  'data': {'from': 1688149800000,
   'to': 1695839400000,
   'transactionData': [{'name': 'Merchant payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 9868299757,
       'amount': 4686944326058.0}]},
    {'name': 'Peer-to-peer payments',
     'paymentInstruments': [{'type': 'TOTAL',
       'count': 5929662466,
       'amount': 18342686827713.0}]},
    {'name': 'Recharge & bill payments',
     'paymentInstruments': [{'type': 'TOTAL',

In [71]:
collected_data4=[]
for country in countries:
    for year in years:
        for data in datas:
            try:
                with open(f'/Users/bootlabs/guvi project-1/pulse/data/aggregated/transaction/country/india/state/{country}/{year}/{data}') as file:
                    data=json.load(file)
                    collected_data4.append(data)
            except Exception as error :
                print(f'error due to {error}')

In [72]:
collected_data4=[]
for year in years:
    for data in datas:
        try:
            with open(f'/Users/bootlabs/guvi project-1/pulse/data/aggregated/user/country/india/{year}/{data}') as file:
                data=json.load(file)
                collected_data4.append(data)
        except Exception as error :
            print(f'error due to {error}')

In [73]:
collected_data5=[]
for country in countries:
    for year in years:
        for data in datas:
            try:
                with open(f'/Users/bootlabs/guvi project-1/pulse/data/aggregated/user/country/india/state/{country}/{year}/{data}') as file:
                    data=json.load(file)
                    collected_data5.append(data)
            except Exception as error :
                print(f'error due to {error}')

In [74]:
pd.json_normalize(collected_data5)

,success,code,responseTimestamp,data.aggregated.registeredUsers,data.aggregated.appOpens,data.usersByDevice
0,True,SUCCESS,1630501494545,3336450,0,"[{'brand': 'Xiaomi', 'count': 836581, 'percent..."
1,True,SUCCESS,1630501494940,4402540,0,"[{'brand': 'Xiaomi', 'count': 1113800, 'percen..."
2,True,SUCCESS,1630501495385,5427617,0,"[{'brand': 'Xiaomi', 'count': 1385112, 'percen..."
3,True,SUCCESS,1630501495715,6857409,0,"[{'brand': 'Xiaomi', 'count': 1753802, 'percen..."
4,True,SUCCESS,1630501496432,8283019,0,"[{'brand': 'Xiaomi', 'count': 2110547, 'percen..."
...,...,...,...,...,...,...
947,True,SUCCESS,1706092807868,30064546,1467442959,None
948,True,SUCCESS,1714727695210,31306843,633526507,None
949,True,SUCCESS,1722517816191,32540397,704276274,None
950,True,SUCCESS,1739974344099,33612828,709864323,None
951,True,SUCCESS,1739974566918,34750181,1994940763,None